jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Pull Selenoid images
        run: |
          docker pull selenoid/vnc_chrome:128.0
          docker pull selenoid/video-recorder:latest-release

      - name: Run Selenoid
        run: docker compose -f docker-compose.yml up -d

      - name: Wait for Selenoid
        run: |
          until curl -s http://127.0.0.1:4444/status | grep -q '"ready":true'; do
            echo "Waiting for Selenoid..."
            sleep 2
          done

      - name: Run tests
        run: mvn test

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./target/surefire-reports/html

      - name: Upload video
        uses: actions/upload-artifact@v4
        with:
          name: video
          path: ./video

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: ./logs
